<?php $this->layout('layout::default', ['title' => 'TracTrak']) ?>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        Find a meet:
    </div>
    <div class="col-md-2"></div>
</div>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        Ongoing meets:
    </div>
    <div class="col-md-2"></div>
</div>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        Upcoming meets:
    </div>
    <div class="col-md-2"></div>
</div>

<p>background-color: #565656;<br>
    color: #39ff14;<br>
    <a href="http://www.colorhexa.com/39ff14">http://www.colorhexa.com/39ff14</a></p>

